#####################################################
##
## AISafe
##
#####################################################

persistence.repositoryFactory=eapli.aisafe.persistence.jpa.JpaRepositoryFactory
#persistence.repositoryFactory=eapli.aisafe.persistence.inmemory.InMemoryRepositoryFactory
ui.menu.layout=horizontal
persistence.persistenceUnit=eapli.aisafe
