@startuml sd_collaborator
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
title Register Collaborator\nInvariant: SecurityClearance must have a valid expiry date (sec. 3.1.1)

participant ":RegisterCollaboratorController" as CTRL
participant "collaboratorRepository\n:CollaboratorRepository" as REPO
participant "collaborator\n:Collaborator" as COL
participant "clearance\n:SecurityClearance" as SC
participant "assessment\n:SkillsAssessment" as SA

-> CTRL : registerCollaborator(name, position, clearanceExpiryDate, assessmentDate, companyID, systemUserID)
activate CTRL

CTRL -> COL ** : create(name, position, clearanceExpiryDate, assessmentDate, companyID, systemUserID)
activate COL

COL -> COL : ensureNameNotEmpty()

COL -> SC ** : new SecurityClearance(clearanceExpiryDate)
activate SC
SC -> SC : ensureExpiryDateValid()
SC --> COL :
deactivate SC

COL -> SA ** : new SkillsAssessment(assessmentDate)
activate SA
SA -> SA : ensureDateRecorded()
SA --> COL :
deactivate SA

COL --> CTRL :
deactivate COL

CTRL -> REPO : save(collaborator)
activate REPO
REPO --> CTRL :
deactivate REPO

deactivate CTRL
@enduml
