@startuml sd_flight
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
title Create Flight\nInvariant: FlightDesignator unique; FlightType must match DepartureSchedule (sec. 3.2)

participant ":CreateFlightController" as CTRL
participant "flightRepository\n:FlightRepository" as REPO
participant "flight\n:Flight" as FL
participant "designator\n:FlightDesignator" as FD
participant "schedule\n:DepartureSchedule" as DS

-> CTRL : createFlight(designator, flightType, departureSchedule, arrivalTime, routeID, aircraftID, pilotID)
activate CTRL

CTRL -> REPO : isFlightDesignatorUnique(designator)
activate REPO
REPO --> CTRL : true
deactivate REPO

CTRL -> FL ** : create(designator, flightType, departureSchedule, arrivalTime, routeID, aircraftID, pilotID)
activate FL

FL -> FD ** : new FlightDesignator(designator)
activate FD
FD -> FD : ensureFormatValid()
FD --> FL :
deactivate FD

FL -> DS ** : create(flightType, departureSchedule)
activate DS
DS -> DS : ensureScheduleMatchesFlightType()
DS --> FL :
deactivate DS

FL --> CTRL :
deactivate FL

CTRL -> REPO : save(flight)
activate REPO
REPO --> CTRL :
deactivate REPO

deactivate CTRL
@enduml
